const FOLDER_ID = '1GmdG9H5wJ2d3_5KFuKLlUlseOzXY9gGU';
const LOG_SHEET_NAME = 'SlideExtractor Users';

function jsonResponse(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function getOrCreateLogSheet_() {
  const files = DriveApp.getFilesByName(LOG_SHEET_NAME);
  let ss;
  if (files.hasNext()) {
    ss = SpreadsheetApp.openById(files.next().getId());
  } else {
    ss = SpreadsheetApp.create(LOG_SHEET_NAME);
    const sheet = ss.getSheets()[0];
    sheet.appendRow([
      'timestamp',
      'job_id',
      'email',
      'newsletter_opt_in',
      'youtube_url',
      'video_title',
      'slides_detected',
      'drive_url'
    ]);
  }
  return ss.getSheets()[0];
}

function doPost(e) {
  try {
    const body = JSON.parse(e.postData.contents || '{}');
    const expectedSecret = PropertiesService.getScriptProperties().getProperty('DRIVE_BRIDGE_SECRET');

    if (!expectedSecret || body.secret !== expectedSecret) {
      return jsonResponse({ ok: false, error: 'Unauthorized' });
    }

    if (!body.pdf_base64 || !body.email || !body.filename) {
      return jsonResponse({ ok: false, error: 'Missing pdf_base64, email, or filename' });
    }

    const folder = DriveApp.getFolderById(FOLDER_ID);
    const bytes = Utilities.base64Decode(body.pdf_base64);
    const blob = Utilities.newBlob(bytes, MimeType.PDF, body.filename);
    const file = folder.createFile(blob);

    // Anyone with the link can view/download the individual PDF.
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
    const url = `https://drive.google.com/file/d/${file.getId()}/view?usp=sharing`;

    const sheet = getOrCreateLogSheet_();
    sheet.appendRow([
      new Date(),
      body.job_id || '',
      body.email,
      body.newsletter === true,
      body.youtube_url || '',
      body.title || '',
      Number(body.slides || 0),
      url
    ]);

    const subject = `Your SlideExtractor PDF${body.title ? ': ' + body.title : ''}`;
    const message = [
      'Your SlideExtractor PDF is ready.',
      '',
      body.title ? `Video: ${body.title}` : '',
      body.slides ? `Slides detected: ${body.slides}` : '',
      '',
      `Open or download the PDF: ${url}`,
      '',
      'Generated by SlideExtractor',
      'Robotics Computing Lab · Tecnológico de Monterrey'
    ].filter(Boolean).join('\n');

    MailApp.sendEmail(body.email, subject, message);

    return jsonResponse({
      ok: true,
      file_id: file.getId(),
      url: url,
      emailed: true
    });
  } catch (err) {
    return jsonResponse({ ok: false, error: String(err && err.message ? err.message : err) });
  }
}
